# Generated by Django 2.1.5 on 2019-01-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_manager_app', '0002_stuendt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stuendt',
            new_name='Student',
        ),
    ]
