# Generated by Django 2.1.5 on 2019-01-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_manager_app', '0003_auto_20190120_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='max_students',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
