# Generated by Django 2.1.5 on 2019-01-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_manager_app', '0005_auto_20190120_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_identification',
            field=models.CharField(default='jSX74lgF7W', editable=False, max_length=20),
        ),
    ]
